[package]
name = "p2p_keys"
version = "0.1.0"
authors = ["Michal Swietek <michal.swietek@cardinals.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = { version ="0.38", features = []}
