version: "3.7"
services:

  # TODO : push slack notification when updating image
  # TODO : configure container to ship logs to cloudwatch

  watchtower:
    image: containrrr/watchtower:latest
    command: --label-enable --cleanup --interval 600 # 600
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  aleph-node:
    image: public.ecr.aws/x2t8a1o3/aleph-node:latest
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
         ./aleph-node purge-chain --chain $CHAIN_NAME --base-path $BASE_PATH -y
         ./aleph-node --validator --chain $CHAIN_NAME --base-path $BASE_PATH --name $NODE_NAME --node-key-file $NODE_KEY_PATH  --rpc-port 9933 --ws-port 9944 --port 30334 --rpc-cors all --rpc-methods Safe --execution Native --no-prometheus --no-telemetry --reserved-only --reserved-nodes $RESERVED_NODES
    container_name: aleph-node
    expose:
      - 9933
      - 9944
      - 30334
    ports:
      - 9933:9933
      - 9944:9944
      - 30334:30334
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /home/$USER/data/:/tmp/
    restart: on-failure
