version: "3.7"
services:

  watchtower:
    image: containrrr/watchtower:latest
    command: --label-enable --cleanup --interval 600 # checks for new image every 10 minutes
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  aleph-node:
    image: public.ecr.aws/x2t8a1o3/aleph-node:latest
    entrypoint: ["/bin/sh","-c"]
    # NOTE : this container runs without any sandboxing, pretty much like a native host process
    privileged: true
    network_mode: host
    command:
      - |
         ./aleph-node purge-chain --chain $CHAIN_NAME --base-path $BASE_PATH -y
         ./aleph-node --validator --chain $CHAIN_NAME --base-path $BASE_PATH --name $NODE_NAME --node-key-file $NODE_KEY_PATH  --rpc-port 9933 --ws-port 9944 --port 30334 --rpc-cors all --rpc-methods Safe --execution Native --no-prometheus --no-telemetry --reserved-only --reserved-nodes $RESERVED_NODES -lafa=debug -lAlephBFT=trace
    container_name: aleph-node
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./data/:/tmp/
    environment:
      - RUST_LOG=info
    logging:
       driver: "awslogs"
       options:
          awslogs-region: eu-west-1 # NOTE: explicitely store logs from all instances in one region, where they can be shipped to ElasticSearch and Kibana
          awslogs-group: "devnet"
          awslogs-stream: $NODE_NAME
    restart: on-failure(3)
